# Resolve react_native_pods.rb with node to allow for hoisting
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

project 'HudMap.xcodeproj'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'HudMap' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'HudMapTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Ensure Metal framework is properly linked for react-native-skia
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-skia'
        target.build_configurations.each do |config|
          flags = config.build_settings['OTHER_LDFLAGS'] || ['$(inherited)']
          flags = [flags] unless flags.is_a?(Array)
          has_metal = flags.any? { |f| f.to_s.include?('Metal') }
          unless has_metal
            flags << '-framework' << 'Metal'
            config.build_settings['OTHER_LDFLAGS'] = flags
          end
        end
      end
    end
  end
end

